development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: webclassificados
  pool: 7
  username: root
  password: admin

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: webclassificados_test
  pool: 7
  username: root
  password: admin

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: webclassificados
  username: root
  password: admin
